### ISSUE TITLE
Add a row to input place of origin

### ISSUE THREAD

**Issue by snehil0802** [coronasafe/trucks#1]
In the form being filled by the personnel on field, there should be an option of Place of origin, from where the truck is coming from. It should be a drop down menu having options of only State. 
Possibility of expanding it for districts as well in future.

**Comment by bodhish** [comment]
- [ ] Add states table
- [ ] Link entries with state
- [ ] list states in a form 
- [ ] Add an option to filter by state

![Screenshot from 2020-04-24 14-45-15](https://user-images.githubusercontent.com/14979190/80196053-6e997f80-863a-11ea-9c20-2f468dff4ca8.png)
